version: '3'

services:
  postgresql:
    container_name: dev-web-project
    image: 'bitnami/postgresql:latest'
    # restart: always
    ports:
      - '5440:5432'
    environment:
      - POSTGRESQL_USERNAME=dev
      - POSTGRESQL_PASSWORD=dev
      - POSTGRESQL_DATABASE=dev-web
    volumes:
      - ./postgres-data:/var/lib/postgresql/data